### PR TITLE
Module title input

### PR DESCRIPTION
**Pull request by qwertynerd97**
Allows users to edit the module title by clicking on the title in the header.
The title is saved when the input is blurred, just like google docs
Unlike changing the title in the File menu, this DOES NOT save the Module, and if the Module is reloaded without saving the title will revert back to the previous title

### CODE REVIEW

File: packages/app/obojobo-document-engine/src/scripts/oboeditor/components/code-editor.js [hunk 1]
```diff
@@ -113,6 +114,16 @@ class CodeEditor extends React.Component {
 		})
 	}
 
+	renameModule(label) {
```
Comment (zachberry) [inline packages/app/obojobo-document-engine/src/scripts/oboeditor/components/code-editor.js]: This code is duplicated in page-editor as well - Want to make sure this happens in the same place in case one of these functions are modified

**Comment by zachberry** [comment]
I put in a few tweaks:

* Moves the editing of the draft title into its own component (since its used in two places)
* Slight tweak to style to give a little more padding to the input
* Allows you to hit Enter to commit the change

**Comment by iturgeon** [comment]
I've got some heavy handed updates to this on my fork (WIP).  There's some deep and gnarly complexity to changing titles, copying modules, renaming, etc.  Especially between JSON, XML, and Visual editor.

I'm pretty happy with my current solution, but wondering if everyone thinks removing the 'rename module' file menu option would be ok? (replaced with this edit-in place option)

**Comment by iturgeon** [comment]
from the commit notes: 

The update/save title options were very complicated and needed some updates to simplify.
They do work a little differently in code-editor vs page-editor, but they seem to make sense now.

Copying a module used to be implemented entirely on the client side, this will now use
the route from obojobo-respository to copy a module, simplifying the client and allowing
use to use the server's metadata to track copies better. (we should move that route to obojobo-express)

* editor-title-input keeps temporary state internally now
* editor-title-input handles ctrl+s and Escape key now
* code-editor save title fixes
* removes rename option from the file menu
* file-menu 'copy module' now uses obojobo-repository copy api
* /api/drafts/xxx/copy now accepts a title param and defaults to appending copy to the name
* page-editor update title fixes
* page-editor was renamed to visual-editor
* supporting test changes
* adds editor:renameModule and associated EditorUtil.renameModule
* json/xml parsing for getting and setting titles moved into EditorUtil
* code-editor state vars simplified
* slight optimization in more-info-box to reduce function creation
* code-editor gets new functions `saveAndGetTitleFromCode` & `saveAndSetNewTitleInCode` as part of cleaner flow
* Header.renamePage will now only rename when the title changes
* Header.renamePage now won't allow undefined or null strings in

**Comment by zachberry** [comment]
This also has a lot of conflicts with #1168

File: packages/app/obojobo-document-engine/src/scripts/oboeditor/components/toolbars/file-menu.js [hunk 2]
```diff
@@ -39,20 +20,11 @@ class FileMenu extends React.PureComponent {
...
-			})
-			.then(() => {
-				this.renameModule(moduleId, oldLabel)
-				window.open(window.location.origin + '/editor/visual/' + draftId, '_blank')
-			})
+	copyModule(newTitle) {
+		return APIUtil.copyDraft(this.props.draftId, newTitle).then(result => {
+			ModalUtil.hide()
+			window.open(window.location.origin + '/editor/visual/' + result.value.draftId, '_blank')
+		})
```
[the remark this answers is not in the document]
Comment (iturgeon) [reply packages/app/obojobo-document-engine/src/scripts/oboeditor/components/toolbars/file-menu.js:27]: I think you're right, I moved it.  I went down a rabbit hole of making this whole thing really fancy with nice dialogs and testing ended up killing my drive.  I stashed it into a branch on my fork for now...

**Comment by iturgeon** [comment]
Fixed all the conflicts and found / fixed the `Uncaught TypeError: _this.props.onSave is not a function` - it was part of a bad merge for some reason on fd585ecddee44d0280bd824eead489ff8ddc2350

**Comment by iturgeon** [comment]
Sweet, thanks @qwertynerd97 I'm going to use my radically unchecked power to merge this in now.
